### PR TITLE
add risk full posting env var to the higher environments

### PR DESCRIPTION
**Pull request by rgforsyth**
## What does this pull request do?

Adds the env var for posting full risk information to the pre-prod and prod environments.

## What is the intent behind these changes?

To allow the risks feature to go live

### CODE REVIEW

**Comment by rgforsyth** [comment]
Do not merge yet

**Review by tomsmyers — APPROVED** [review]

**Comment by sldblog** [comment]
📝 As far as I know we've been asked to not enable this until Friday morning

**Comment by sldblog** [comment]
Never mind, I just realised it's the API not the UI

**Comment by sldblog** [comment]
Sorry -- thanks!

**Pull request merged**
