### PR TITLE
build docker image on PR branches, but do not publish

### PR DESCRIPTION
**Pull request by tomsmyers**
## What does this pull request do?

runs circleci build_docker job on all branches, but only publishes to quay.io on main

## What is the intent behind these changes?

validate changes to dockerfile in PRs before merging to main

### CODE REVIEW

**Comment by sldblog** [comment]
Looks like it needs a token in CircleCI secrets

**Comment by tomsmyers** [comment]
working now :) 

looks like we have to address some known high severity CVEs. will look tomorrow.

**Comment by sldblog** [comment]
🎉 

Seems like all of them come from the base image itself https://snyk.io/test/docker/openjdk%3A11-jre-slim?severity=high&policy=open&tab=issues

**Comment by tomsmyers** [comment]
@sldblog it looks like using the alpine tags of openjdk is not a good idea based on the docs:

```
What this means is that Alpine based images are only released for early access release versions of OpenJDK. Once a particular release becomes a "General-Availability" release, the Alpine version is dropped from the "Supported Tags"; they are still available to pull, but will no longer be updated.
```

**Comment by sldblog** [comment]
👍 Indeed. It looks like https://hub.docker.com/r/adoptopenjdk/openjdk11 is unofficial as well.

**Comment by tomsmyers** [comment]
@sldblog i've disabled the vulnerability scanning on this PR for the time being. just to unblock this until we sort out the base image issues.

**Review by sldblog — APPROVED** [review]

**Pull request merged**
