### PR TITLE
split not null migration into seperate transaction

### PR DESCRIPTION
**Pull request by tomsmyers**
## What does this pull request do?

split not null migration into seperate transaction. previously i split the migration into seperate files, but the naming convention meant the migration was still applied as one. this should finally fix this issue.

## What is the intent behind these changes?

unblock the deploy

### CODE REVIEW

**Review by Gweaton — APPROVED** [review]
Let's see if this fixes the issue

**Review by sldblog — CHANGES_REQUESTED** [review]
Locally, this still fails for me 🤔

**Review by sldblog — COMMENTED** [review]
Pushed an `IS NULL` change up -- passes locally now

**Comment by tomsmyers** [comment]
> Pushed an `IS NULL` change up -- migration works locally now
> 
> Totally missed this a few times in the past reviews 😅

thank you !

**Review by sldblog — APPROVED** [review]

**Comment by sldblog** [comment]
naughty self-approval there 🙈

**Pull request merged**
