### PR TITLE
Add cluster migration annotations

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

Add cluster migration annotations

Similar to
- https://github.com/ministryofjustice/hmpps-interventions-ui/pull/991

## What is the intent behind these changes?

This is to allow migration of the current Kubernetes cluster to AWS'
Elastic Kubernetes Service

Following https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrate-to-live-ingress-annotation.html

### CODE REVIEW

**Comment by sldblog** [comment]
[❗️Need to migrate dev/research env to EKS cluster in Cloud Platform](https://trello.com/c/UQgzJJr6/122-%E2%9D%97%EF%B8%8Fneed-to-migrate-dev-research-env-to-eks-cluster-in-cloud-platform)

**Review by tomsmyers — APPROVED** [review]
LGTM - although isn't this included in the generic helm chart stuff?

**Comment by sldblog** [comment]
@tomsmyers it is -- but service is a bit involved with the data dictionary put on top of the same ingress

**Comment by sldblog** [comment]
Thank you!

**Pull request merged**
