### PR TITLE
correct duplicates in FBD NW

### PR DESCRIPTION
**Pull request by kth13**
## What does this pull request do?

- delete some duplicates data for the desired outcomes of FBD-NW
- correct some cases for some of the desired outcomes of FBD-NW

## What is the intent behind these changes?

- There are some duplicate data in the desired outcomes of FBD-NW and it needs clean up

### CODE REVIEW

**Review by sldblog — COMMENTED** [review]
@kth13 Please could you attach the resulting 'final' outcomes to the description? It makes it simpler to review what will be left

**Comment by kth13** [comment]
> @kth13 Please could you attach the resulting 'final' outcomes to the description? It makes it simpler to review what will be left

Attaching the final outcome
[data-1669826524689.csv](https://github.com/ministryofjustice/hmpps-interventions-service/files/10125328/data-1669826524689.csv)

**Comment by sldblog** [comment]
Thanks, there seem to be a few groups still left, marked with similar letters:

duplicate | id  |description 
-- | -- | -- |
?  | 86656efa-de29-4a58-b7d0-25c8ac1a15b4 | Service user gains quick access to universal credit. 
A | 8ec86c5f-0788-446a-bc4b-108e1c83dc25 | Service user has access to appropriate financial products, advice and/or services. 
B  | 7058935b-cc4d-43a9-8bf5-a0ef4575d746 | Service user on probation financial management skills are developed and/or enhanced including online banking. 
  | 20c0df29-4e0e-42ef-9f19-b7d90d06a420 | The person referred is supported to complete tasks that they would not otherwise be able to do whilst being in custody e.g. support with banking or debt management. 
C  | af754368-3d86-4c6e-90f1-760b03b6fa59 | Pathways are established to help the person referred to maintain and sustain an income, safely manage money and reduce debt.
C  | d8fb1e8d-43db-4a42-abda-0c64116ab441 | Pathways are established to help service user maintain and sustain an income, safely manage money and reduce debt. 
B  | f869b53d-14d6-48bf-842f-f988ef845ee6 | Service user’s financial management skills are developed and/or enhanced, including online banking skills. 
A  | a1d1d743-158c-4b13-b370-397f247484da | The person referred has access to appropriate financial products, advice and/or services 
?  | aa8da6a3-c633-483d-a0e0-6716c990975b | The person referred gains quick access to universal credit, including pre-release referrals. 
  | 39393e5f-48d2-4981-84d1-e23d762f65b8 | The person referred can successfully navigate the benefits system
B  | a0e18ea2-9982-43c5-9155-8a07ec88fe75 | The person referred’s financial management skills are developed and/or enhanced, including online banking skills 

Not sure what to do with `?`

**Comment by kth13** [comment]
New desired outcomes for FBD-NW

**Review by sldblog — APPROVED** [review]

**Pull request merged**
