### PR TITLE
Tidyup migrate changelog backfill

### PR DESCRIPTION
**Pull request by awhodgson256**
## What does this pull request do?

Removes code associated with the migrate changelog backfill job which has run successfully in production.

## What is the intent behind these changes?

To remove code that is no longer used and thus prevent the need to maintain it. Also prevent job runs that aren't required.

As defined in
[IPB-141](https://dsdmoj.atlassian.net/browse/IPB-141)

[IPB-141]: https://dsdmoj.atlassian.net/browse/IPB-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sldblog** [comment]
@awhodgson256 Could you add the IPB-NUM as text to the description, please? It will link the Jira ticket with this PR automatically

**Review by sldblog — COMMENTED** [review]
Nice. One ask for better cohesion

**Comment by kth13** [comment]
Looking good but I believe we need to rename to branch to make branch-name-validator / check-jira-prefix (pull_request)  check pass

**Comment by sldblog** [comment]
I think we can ignore the `branch-name-validator / check-jira-prefix` CI failure. We know this existed before that rule came into force.

However, could this be rebased, please? It shows a lot of unrelated commits

**Comment by awhodgson256** [comment]
Tidied up the commit history and pushed changes @sldblog .

**Review by kth13 — APPROVED** [review]
LGTM

**Pull request merged**
